package com.user.foodzamo.OrderFood;

import android.app.Application;

/**
 * Created by user on 10/29/2016.
 */

public class Global{
 public  String products[] = {

         //185 to 190 Colonies/Centers
         "ABV IIITM",
         "Achileshwar Mandir",
         "Adarsh Colony Shinde Ki Chhawani",
         "Ajay Colony,Gadhaipura",
         "Alkapuri",
         "Amity University",
         "Amkoh",
         "Anand Nagar",
         "Anupam Nagar Patel Nagar",
         "Apna Ghar Colony Vinay Nagar",
         "Ashok Vihar Colony",
         "Bajrang Vihar Colony,Darpan Colony",
         "Bala Bai Ka Bazar, Lohiya Bazar",
         "Balwant Nagar",
         "Bank Colony Mahalgaon",
         "Bankers Colony,Darpan Colony",
         "Bhao Ka Bazar,Bakshi Ki Goth",
         "Bhodapur ,Anand Nagar",
         "Cancer Pahadi",
         "Chana Kothar",
         "Chanakya Puri ,Darpan Colony",
         "Chandan Colony",
         "Chatri Sabji Mandi,Jiyaki Chowk",
         "Chawri Bazar, Bakshi Ki Goth",
         "Chetak Puri, Lashkar",
         "City Centre Mahalgoan",
         "Dahi Mandi,Sarafa Bazar ",
         "Dal Bazar",
         "Danchinati Colony(Ghosipura)",
         "Darpan colony",
         "Daulat Gunj",
         "Defence Colony(Gandhinagar)",
         "Dholi Bua Kapul(Shriram Colony)",
         "Didwanaoli(Daulant Ganj)",
         "Durgapuri",
         "Dwarakapuri(Lashkar)",
         "Ekata Nagar(Vinay Nagar)",
         "Fortview Colony",
         "Gadway ki goth(Lala ki bazar)",
         "Gandhi Market(JyajiChowk)",
         "Gandhinagar",
         "Ganjiwala Mohalla(Madhav Ganj)",
         "Gargaj Colony(Laxmi Colony)",
         "Gastka Tazia Chauraha(Daulant Ganj)",
         "Geeta Colony(Lashkar)",
         "Ghasmandi",
         "Ghauspura",
         "Ghosipura",
         "Golpamariya",
         "Goverdhan Colony(Morar)",
         "Govindpuri",
         "Gubbara Phatak(Daal Bazar)",
         "Gudi Gudi ka nakar(Lashkar)",
         "Gurunanak Nagar",
         "Hanman Nagar(Morar)",
         "Hanuman CHauraha(Shekh ki Bhagiya)",
         "Hargovindpuram(Tulsi vihar nagar)",
         "Harishankarpuram(Shri ram colony)",
         "Hazira Chowk(Tansen Nagar)",
         "Helipad Colony(Lashkar)",
         "Hem Singh ki Pared",
         "Hurawali",
         "Indramani Nagar(Thatipur)",
         "Jagrati Nagar",
         "Jai villas parijar(Lashkar)",
         "Janak Ganj(Jiyaji Chowk)",
         "Janak Taal(Gurunanak Road)",
         "Jawahar Colony(Lashkar)",
         "Jayendra Gunj(Shinde ki chhwani)",
         "Jinsi Nala(Madhav Ganj)",
         "Jiwaji Chowk(Lashkar)",
         "Kailash Nagar(Mahalgaon)",
         "Kailash Vihar(Tusi Vihar Colony)",
         "Kala Saiyad",
         "Kampoo",
         "Katigati",
         "Khurjewala Mohalla(Daulat Colony)",
         "Krishna Vihar(Thatipur)",
         "Kumharpura Chauraha(Dardan COlony)",
         "Kuswah Market(Deen Dayal Nagar)",
         "Kuswah Mohalla(Shilpa Studio)",
         "Lalaka Bazar",
         "Lalitpur Colony",
         "Lashkar",
         "Laxmi Colony",
         "Laxmi Ganj",
         "Laxmipuram(Kishan Bagh)",
         "Loha Mandi(Gol Dahariya)",
         "Lohiya Bazar",
         "MLB Colony(Lashkar)",
         "Madhav Ganj",
         "Madhav Nagar",
         "Madhuwan Enclave(Mahalgaon)",
         "Mahalgaon",
         "Maharana Pratap nagar(Lashkar)",
         "Mahaver Bhavan(Morar)",
         "Mama ka Bazar(Laskpur)",
         "MasgiBazar(jiyaji Chowk)",
         "Mayur Nagar(Thatipur)",
         "Mor Bazar(Jiyaji Chowk)",
         "Nagarik Sahakar Bank)",
         "Navgrah Colony(Shri ram Colony)",
         "Nawab Singh Colony(Harishankar Colony)",
         "Naya bazar(ward No.46)",
         "Nehru Colony(Thatipur)",
         "New Colony(Birla Nagar)",
         "New Dayga Gudi",
         "New Govindpuri(Mahalgaon)",
         "New Kushak Nagar",
         "New Prem Nagar",
         "New Reshma Colony(Birla Nagar)",
         "New Shri Krishna Nagar(Gole ka Mandir Road)",
         "New Vivek Nagar(Thatipur)",
         "Nimbaji ki Khoh(Laxmi Gunj)",
         "Panchivati Nagar(Lashkar)",
         "Pant Nagar(Mahalgaon)",
         "Parasvihar Colony(Vijay Nagar)",
         "Pardhi Mohalla(Shekh ki Bhagiya)",
         "Patankar Chauraha(Khrjewala Mohalla)",
         "Patel Ngar",
         "Payga Colony(Shekh ki Bhagiya)",
         "Phool Bagh(Lashkar)",
         "Police Colony",
         "Pragati Nagar",
         "Prem Nagar",
         "Pritampuram Colony(Army Bazariya)",
         "RM Colony(Lalaka Bazar)",
         "RP Colony(Durgapuri)",
         "Radhika Vihar(Madhav Gunj)",
         "Raghavendra Nagar",
         "Railway COlony(Thatipur)",
         "Ramanuj Nagar",
         "Ramji ka pura",
         "Ramtapura(Tansen Nagar)",
         "Ranipura",
         "Ratan Colony(Shekh ki Bhagiya)",
         "Rati Nagar",
         "Ravi nagar(Lashkar)",
         "Roshini Ghar(Lashkar)",
         "Sadashiv Nagar(Vinay Nagar)",
         "Saketnagar(Durgapuri)",
         "Samadhiya Colony(Kala Saiyad)",
         "Sarafa bazar(Daulant Gunj)",
         "Saraswati Nagar",
         "Sathbhai ki goth",
         "Satyadev Nagar",
         "Scindia Nagar(Surya Nagar)",
         "Seva Nagar(Prem Nagar)",
         "Sewak Nagar",
         "Shankarchowk(Lalitpur Colony)",
         "Sharda Vihar(Mahalgaon)",
         "Shastri Nagr Thatipur",
         "Shekh Ki Bagiya",
         "Shinde Ki Chhawani",
         "Shiv Colony(Gayatri Nagar)",
         "Shiv Sadan",
         "Shiv Shaktipuram",
         "Shivaji Colony",
         "Shivaji Nagar, Thatipur",
         "Shri Krishna Colony, Hem Singh Ki Pared",
         "Shri Ram Nagar Colony",
         "Shri Vihar Colony, Ghosipura",
         "Shubhash Nagar, Birla Nagar",
         "Sikander Kampo, Chana Kothar",
         "Sindhi Colony",
         "Sukkhar Colony, Dana Oli",
         "Suresh Nagar, Thatipur",
         "Surya Nagar",
         "Tagore Nagar, Patel Nagar",
         "Tansen Nagar",
         "Tansen Residency Chauraha",
         "Tara Ganj, Loha Mandi, Gol Pahariya",
         "Thatipur",
         "Thatipur Gaon, Thatipur",
         "Tilak Nagar, Radhika Nagar",
         "Vasant Vihar, Lashkar",
         "Vijay Nagar",
         "Vijay Nagar Extension, Basvant Vihar Colony",
         "Vikas Nagar, Lashkar",
         "Vinay Nagar",
         "Vinay Nagar Chowk",
         "Vivek Vihar",
         "Yadav Colony, Lashkar",
         "Yamuna Nagar, Darpan Colony",
 };
}
