package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocCityCenter {
    public String below_five[]={
            "Achileshwar Mandir",
            "Adarsh Colony Shinde Ki Chhawani",
            "Alkapuri",
            "Amkoh",
            "Anupam Nagar Patel Nagar",
            "Ashok Vihar Colony",
            "Bala Bai Ka Bazar, Lohiya Bazar",
            "Balwant Nagar",
            "Bank Colony Mahalgaon",
            "Bajrang Vihar Colony,Darpan Colony",
            "Bankers Colony,Darpan Colony",
            "Bhao Ka Bazar,Bakshi Ki Goth",
            "Cancer Pahadi",
            "Chandan Colony",
            "Chetak Puri Lashkar",
            "City Centre Mahalgoan",
            "Dahi Mandi,Sarafa Bazar ",
            "Chanakya Puri ,Darpan Colony",
            "Dal Bazar",
            "Darpan colony",
            "Daulat Gunj",
            "Kailash Nagar(Mahalgaon)",
            "Kailash Vihar(Tusi Vihar Colony)",
            "Kampoo",
            "MasgiBazar(jiyaji Chowk)",
            "Khurjewala Mohalla(Daulat Colony)",
            "Krishna Vihar(Thatipur)",
            "Lalaka Bazar",
            "Lalitpur Colony",
            "Lashkar",
            "Madhav Ganj",
            "Madhav Nagar",
            "Madhuwan Enclave(Mahalgaon)",
            "Mahalgaon",
            "Mama ka Bazar(Laskpur)",
            "Mayur Nagar(Thatipur)",
            "Navgrah Colony(Shri ram Colony)",
            "Nawab Singh Colony(Harishankar Colony)",
            "Naya bazar(ward No.46)",
            "Nehru Colony(Thatipur)",
            "New Colony(Birla Nagar)",
            "New Govindpuri(Mahalgaon)",
            "New Kushak Nagar",
            "New Reshma Colony(Birla Nagar)",
            "New Vivek Nagar(Thatipur)",
            "Panchivati Nagar(Lashkar)",
            "Pant Nagar(Mahalgaon)",
            "Parasvihar Colony(Vijay Nagar)",
            "Seva Nagar(Prem Nagar)",
            "Shastri Nagar(Thatipur)",
            "Shankarchowk(Lalitpur Colony)",
            "Sharda Vihar(Mahalgaon)",
            "Shekh ki Bhagiya",
            "Shinde ki chhwani",
            "Ramtapura(Tansen Nagar)",
            "Ravi nagar(Lashkar)",
            "Roshini Ghar(Lashkar)",
            "RP Colony(Durgapuri)",
            "Saketnagar(Durgapuri)",
            "Sarafa bazar(Daulant Gunj)",
            "Saraswati Nagar",
            "Satyadev Nagar",
            "Pardhi Mohalla(Shekh ki Bhagiya)",
            "Patankar Chauraha(Khrjewala Mohalla)",
            "Patel Ngar",
            "Payga Colony(Shekh ki Bhagiya)",
            "Police Colony",
            "Prem Nagar",
            "Raghavendra Nagar",
            "Railway COlony(Thatipur)",
            "Ramanuj Nagar",
            "Didwanaoli(Daulant Ganj)",
            "Defence COlony(Gandhinagar)",
            "Durgapuri",
            "Dwarakapuri(Lashkar)",
            "Gandhi Market(JyajiChowk)",
            "Gandhinagar",
            "Gastka Tazia Chauraha(Daulant Ganj)",
            "Geeta Colony(Lashkar)",
            "Govindpuri",
            "Gubbara Phatak(Daal Bazar)",
            "Hazira Chowk(Tansen Nagar)",
            "Hargovindpuram(Tulsi vihar nagar)",
            "Harishankarpuram(Shri ram colony)",
            "Helipad Colony(Lashkar)",
            "Hurawali",
            "Indramani Nagar(Thatipur)",
            "Jai villas parijar(Lashkar)",
            "Jayendra Gunj(Shinde ki chhwani)",
            "Jiwaji Chowk(Lashkar)",
            "Shastri Nagr Thatipur",
            "Shinde Ki Chhawani",
            "Shiv Shaktipuram",
            "Shivaji Colony",
            "Sukkhar Colony, Dana Oli",
            "Tagore Nagar, Patel Nagar",
            "Tansen Nagar",
            "Tansen Residency Chauraha",
            "Thatipur Gaon, Thatipur",
            "Vasant Vihar, Lashkar",
            "Vijay Nagar",
            "Vijay Nagar Extension, Basvant Vihar Colony",
            "Vikas Nagar, Lashkar",
            "Vivek Vihar",
            "Yadav Colony, Lashkar",
            "Suresh Nagar, Thatipur",
            "Thatipur",
            "Shivaji Nagar, Thatipur",
            "Shri Ram Nagar Colony",
            "Yamuna Nagar, Darpan Colony"
    };
}
