package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocCooks {
    public String below_five[]=
            {
                    "Achileshwar Mandir",
                    "Adarsh Colony Shinde Ki Chhawani",
                    "Alkapuri",
                    "Amkoh",
                    "Anupam Nagar Patel Nagar",
                    "Apna Ghar Colony Vinay Nagar",
                    "Ashok Vihar Colony",
                    "Bala Bai Ka Bazar, Lohiya Bazar",
                    "Balwant Nagar",
                    "Bank Colony Mahalgaon",
                    "Bhao Ka Bazar,Bakshi Ki Goth",
                    "Bhodapur ,Anand Nagar",
                    "Cancer Pahadi",
                    "Chana Kothar",
                    "Chandan Colony",
                    "Chatri Sabji Mandi,Jiyaki Chowk",
                    "Chawri Bazar, Bakshi Ki Goth",
                    "Chetak Puri Lashkar",
                    "City Centre Mahalgoan",
                    "Dahi Mandi,Sarafa Bazar ",
                    "Dal Bazar",
                    "Daulat Gunj",
                    "Dahi Mandi(Sarafa Bazar)",
                    "Dal Bazar",
                    "Daulat Ganj",
                    "Didwana Oli(Daulat Ganj)",
                    "Gastka Tazia(Daulant Ganj)",
                    "Geeta Colony( Lashkar)",
                    "Gubbara Phatak(Daal Bazar)",
                    "Helipad Colony(Lashkar)",
                    "Jai Vilas Pariyar(Lashkar)",
                    "Jayendra Gunj(Shinde Ki Chhawani)",
                    "Khurjewala Mohalla",
                    "Lalitpur Colony",
                    "Lashkar",
                    "Maharanapratap Nagar",
                    "Naya Bazar",
                    "Pardhi Mohalla",
                    "Patankar Chauraha(Khurjewala Mohalla)",
                    "Payga Colony",
                    "Roshini Ghar",
                    "Sarafa Bazar(Daulat Ganj)",
                    "Sathe Ki Goth",
                    "Sbi Colony",
                    "Shankar Chowk",
                    "Shanakr Colony",
                    "Shekh Ki Bagiya",
                    "Sukkhar Colony( Dana Oli)",
                    "Gandhi Market(Chawri Bazar)",
                    "Ghosipura",
                    "Hanuman Chauraha(Shekh Ki Bagiya)",
                    "Janak Ganj(Jiyaji Chowk)",
                    "Jivaji Chowk",
                    "Jinsinala",
                    "Jivaji Ganj",
                    "Jiyaji Chowk",
                    "Kati Gati",
                    "Khasi Bazar",
                    "Lohiya Bazar",
                    "Madhav Ganj",
                    "Madhav Nagar",
                    "Mor Bazar",
                    "Nagarik Sahakari Bank",
                    "Phool Bagh(Lashkar)",
                    "Pragati Nagar",
                    "Ratan Colony( Shekh Ki Bagiya)",
                    "Rati Nagar",
                    "Ravi Nagar(Lashkar)",
                    "Sath Bhai Ki Goth",
                    "Sbi Chauraha",
                    "Jawahar Colony(Lashkar)",
                    "Defence Colony(Gandhinagar)",
                    "Dwaraka Puri(Lashkar)",
                    "Gadway Ki Gath(Lala Ki Bazar)",
                    "Gandhinagar",
                    "Ganjiwala Mohalla",
                    "Golpahariya",
                    "Harishankar Puram(Shriram Colony)",
                    "Jagrathi Nagar",
                    "Kusawah Mohalla(Shilpa Studio)",
                    "Lalaka Bazar",
                    "Laxmi Colony",
                    "Loha Mandi",
                    "Mamaka Bazar",
                    "Mlb Colony(Lashkar)",
                    "Navgrah Colony",
                    "Nawab Singh Colony(Harishankar Puram)",
                    "New Kashak Nagar",
                    "Panchavati Colony(Ghosipura)",
                    "Pant Nagar(Mohalgaon)",
                    "Police Colony",
                    "Radhika Vihar(Madhav Gunj)",
                    "Samadhiya Colony(Kala Saiyad)",
                    "Scindia Nagar",
                    "Shinde Ki Chhaoni",
                    "Shivaji Colony",
                    "Sri Vihar Colony(Ghosipura)",
                    "Sikander Kampo(Chana Kothar)",
                    "Surya Nagar",
                    "Janak Taal(Gurunanak Nagar)",
                    "Dholi Bua Kapul(Shriram Colony)",
                    "Durga Puri",
                    "Ekata Nagar(Vinay Nagar)",
                    "Fort View Colony",
                    "Gargaj Colony(Laxmipuram)",
                    "Gurunanak Nagar",
                    "Hemsingh Ki Pared",
                    "Kampoo",
                    "New Payga Gudi",
                    "Panchivati Nagar",
                    "Paras Vihar Colony",
                    "Prem Nagar",
                    "Raghavendra Nagar(Gwalior)",
                    "Railway Colony",
                    "Ranji Ka Pura",
                    "Rm Colony",
                    "Mohalla(Lashkar)",
                    "Sadashiv Nagar(Vinay Nagar)",
                    "Seva Nagar",
                    "Servak Nagar",
                    "Shadavihar(Mohalgaon)",
                    "Shivaji Nagar",
                    "Sri Krishna Colony",
                    "Ghasmandi",
                    "Ghauspura",
                    "Guda Gudi Ka Nakar(Lashkar)",
                    "Hazira Chowk(Tansen Nagar)",
                    "Hargovindpuram(Tulsi Vihar Nagar)",
                    "Jiwaji University Chauraha",
                    "Kailash Viharkala Saiyad",
                    "Laxmipuram(Kishan Bagh)",
                    "Madhuwan Enclave",
                    "Mahalgaon",
                    "New Colony",
                    "New Govindpuri(Mahalgaon)",
                    "Patel Nagar",
                    "Pritam Puram Colony",
                    "Raj Mandi",
                    "Ramta Pura(Tansen Nagar)",
                    "Ranipura",
                    "Saket Nagar",
                    "Saraswati Nagar",
                    "Satyadev Nagar",
                    "Shiv Sadan",
                    "Sriram Colony",
                    "Sikander Colony",
                    "Sindhi Colony",
                    "Shastri Nagar, Thatipur",
                    "Shinde Ki Chhawani",
                    "Shiv Shaktipuram",
                    "Shivaji Colony",
                    "Shri Vihar Colony, Ghosipura",
                    "Sikander Kampo, Chana Kothar",
                    "Shri Krishna Colony, Hem Singh Ki Pared",
                    "Sukkhar Colony, Dana Oli",
                    "Surya Nagar",
                    "Tansen Nagar",
                    "Tansen Residency Chauraha",
                    "Tara Ganj, Loha Mandi, Gol Pahariya",
                    "Thatipur Gaon, Thatipur",
                    "Tilak Nagar, Radhika Nagar",
                    "Vasant Vihar, Lashkar",
                    "Vijay Nagar",
                    "Vijay Nagar Extension, Basvant Vihar Colony",
                    "Vikas Nagar, Lashkar",
                    "Vinay Nagar",
                    "Vinay Nagar Chowk",
                    "Vivek Vihar",
                    "Yadav Colony",
                    "Sindhi Colony"
            };
}
