package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocFoodzInn {
    public String below_five[]={
            "Achileshwar Mandir",
            "Adarsh Colony Shinde Ki Chhawani",
            "Alkapuri",
            "Amkoh",
            "Anupam Nagar Patel Nagar",
            "Ashok Vihar Colony",
            "Bala Bai Ka Bazar, Lohiya Bazar",
            "Bankers Colony,Darpan Colony",
            "Balwant Nagar",
            "Bank Colony Mahalgaon",
            "Bhao Ka Bazar,Bakshi Ki Goth",
            "Cancer Pahadi",
            "Chana Kothar",
            "Chandan Colony",
            "Chatri Sabji Mandi,Jiyaki Chowk",
            "Chanakya Puri Darpan Colony",
            "Chawri Bazar, Bakshi Ki Goth",
            "Chetak Puri Lashkar",
            "City Centre Mahalgoan",
            "Dahi Mandi,Sarafa Bazar",
            "Dal Bazar",
            "Daulat Gunj",
            "Darpan Bazar",
            "Harishankar Puram(Shriram Colony)",
            "Jai Vilas Parisar(Lashkar)",
            "Lashkar",
            "Madhav Nagar",
            "Maharanapratap Nagar",
            "Nawab Singh Colony(Harishankar Puram)",
            "Roshini Ghar",
            "Dal Bazar",
            "Gastia Tazia Chouraha(Daulant Ganj)",
            "Geeta Colony(Lashkar)",
            "Helipad Colony(Lashkar)",
            "Jayendra Gunj(Shinde Ki Chhawani)",
            "Lalitpur Colony",
            "New Kushak Nagar",
            "Pant Nagar(Mahalgaon)",
            "Pardhi Mohalla",
            "Police Colony",
            "Sbi Colony",
            "Shankar Colony",
            "Dahi Mandi(Sarafa Bazar)",
            "Daulat Ganj",
            "Didwana Oli(Doulat Ganj)",
            "Defence Colony(Gandhinagar)",
            "Dwarakapuri(Lashkar)",
            "Gandhi Market(Khagi)",
            "Gandhinagar",
            "Gubbara Phatak(Daal Bazar)",
            "Jivaji Chowk",
            "Kailash Vihar",
            "Kampoo",
            "Katigali",
            "Khurjewala Mohalla",
            "Laxmi Colony",
            "Mahalgaon",
            "Mlb Colony(Lashkar)",
            "Naya Bazar",
            "Panchivati Nagar",
            "Paras Vihar Colony",
            "Patankar Chauraha(Khurjewala Mohalla)",
            "Payga Colony",
            "Phool Bagh(Lashkar)",
            "Raghavendra Nagar(Gwalior)",
            "Ravi Nagar(Lashkar)",
            "Sarafa Bazar(Doulat Ganj)",
            "Sathe Ki Goth",
            "Shankar Chowk",
            "Sharda Vihar(Mahalgaon)",
            "Shinde Ki Chhaoni",
            "Shivaji Colony",
            "Sukhar Colony(Dana Oli)",
            "Durga Puri",
            "Ganjiwala Mohalla",
            "Ghosipura",
            "Govindpuri",
            "Hanuman Chauraha(Shik Ki Bagiya)",
            "Hargovindpuram(Tulsi Vihar Nagar)",
            "Janak Ganj(Juyayi Chowk)",
            "Jinsinala",
            "Jivaji Ganj",
            "Jiwaji University Chauraha",
            "Jiyaji Chowk",
            "Railash Nagar",
            "Krishna Vihar",
            "Laxmi Ganj",
            "Lohiya Bazar",
            "Madhuwan Enclave",
            "Mor Bazar",
            "Nagarik Sahakari Bank",
            "New Govindpuri(Mahalgaon)",
            "New Prem Nagar",
            "Patel Nagar",
            "Prem Nagar",
            "Railway Colony",
            "Ramanuj Nagar",
            "Ratan Colony(Shekh Ki Bagiya)",
            "Rati Nagar",
            "Mohalla(Lashkar)",
            "Saket Nagar",
            "Saraswati Nagar",
            "Sath Bhai Ki Goth",
            "Sbi Chauraha",
            "Seva Nagar",
            "Servark Nagar",
            "Surya Nagar",
            "Darpan Colony",
            "Gadway Ki Goth(Lala Ki Bazar)",
            "Golpahariya",
            "Hazira Chowk(Tansen Nagar)",
            "Jagrati Nagar",
            "Kuswah Mohalla(Shilpa Studio)",
            "Lalaka Bazar",
            "Loha Mandi",
            "Madhav Ganj",
            "Mama Ka Bazar",
            "Mayur Nagar",
            "New Colony",
            "Panchvati Colony(Ghosipura)",
            "Pragati Nagar",
            "Radhika Vihar(Madhav Gunj)",
            "Raj Mandi",
            "Ramtapura(Tansen Nagar)",
            "Rm Colony",
            "Satyadev Nagar",
            "Scindia Nagar",
            "Shakuntlapuri",
            "Sri Vihar Colony(Ghosipura)",
            "Sikander Kampo(Chana Kothar)",
            "Shubash Nagar(Bula Nagar)",
            "Shastri Nagar, Thatipur",
            "Shinde Ki Chhawani",
            "Shiv Shaktipuram",
            "Shivaji Colony",
            "Shri Vihar Colony, Ghosipura",
            "Sukkhar Colony, Dana Oli",
            "Surya Nagar",
            "NAGAR Tagore Nagar, Patel Nagar",
            "Tansen Nagar",
            "Tansen Residency Chauaraha",
            "Tara Ganj, Loha Mandi, Gol Pahariya",
            "Thatipura Gaon, Thatipur",
            "Tilak Nagar, Radhika Nagar",
            "Vasant Vihar, Lashkar",
            "Vijay Nagar",
            "Vijay Nagar Extension, Basvant Vihar Colony",
            "Vikas Nagar, Lashkar ",
            "Vinay Nagar Chowk",
            "Vivek Vihar",
            "Yadav Colony, Lashkar"
    };
}
