package com.user.foodzamo.OrderFood;

/**
 * Created by user on 12/17/2016.
 */

public class LocGKM {
    public String below_five[]={
            "ABV IIITM",
            "Anupam Nagar Patel Nagar",
            "Ashok Vihar Colony",
            "Amity University",
            "Balwant Nagar",
            "Kampoo",
            "Mayur Nagar(Thatipur)",
            "Nehru Colony(Thatipur)",
            "New Colony(Birla Nagar)",
            "New Reshma Colony(Birla Nagar)",
            "New Vivek Nagar(Thatipur)",
            "Panchivati Nagar(Lashkar)",
            "Seva Nagar(Prem Nagar)",
            "Shastri Nagar(Thatipur)",
            "RP Colony(Durgapuri)",
            "Ramtapura(Tansen Nagar)",
            "Saketnagar(Durgapuri)",
            "Saraswati Nagar",
            "Satyadev Nagar",
            "Patel Ngar",
            "Ajay Colony,Gadhaipura",
            "Bhagat Singh Nagar,Deen Dayal Nagar",
            "Birla Nagar",
            "Kumharpura Chauraha(Dardan Colony)",
            "Kuswah Market(Deen Dayal Nagar)",
            "Laxmi Colony",
            "Mahaver Bhavan(Morar)",
            "MLB Colony(Lashkar)",
            "Nagarik Sahakar Bank)",
            "New Shri Krishna Nagar(Gole ka Mandir Road)",
            "Sewak Nagar",
            "Shiv Colony(Gayatri Nagar)",
            "Shiv Sadan",
            "Ranipura",
            "Ghasmandi",
            "Ghauspura",
            "Goverdhan Colony(Morar)",
            "Hanman Nagar(Morar)",
            "Shiv Colony, Gayatri Nagar",
            "Shiv Sadan",
            "Shubhash Nagar, Birla Nagar",
            "Phool Bagh(Lashkar)",
            "Police Colony",
            "Raghavendra Nagar",
            "Railway COlony(Thatipur)",
            "Defence COlony(Gandhinagar)",
            "Durgapuri",
            "Gandhinagar",
            "Govindpuri",
            "Hazira Chowk(Tansen Nagar)",
            "Hargovindpuram(Tulsi vihar nagar)",
            "Indramani Nagar(Thatipur)",
            "Shastri Nagr Thatipur",
            "Tagore Nagar, Patel Nagar",
            "Tansen Nagar",
            "Tansen Residency Chauraha",
            "Thatipur Gaon, Thatipur",
            "Vasant Vihar, Lashkar",
            "Vijay Nagar Extension, Basvant Vihar Colony",
            "Suresh Nagar, Thatipur",
            "Thatipur",
            "Shivaji Nagar, Thatipur",
            "Shri Ram Nagar Colony",
            "Yamuna Nagar, Darpan Colony"
    };
}

