package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocMotiMahal {
    public String below_five[]=
            {
                    "Achileshwar Mandir",
                    "Adarsh Colony Shinde Ki Chhawani",
                    "Alkapuri",
                    "Anupam Nagar Patel Nagar",
                    "Ashok Vihar Colony",
                    "Bala Bai Ka Bazar, Lohiya Bazar",
                    "Balwant Nagar",
                    "Bank Colony Mahalgaon",
                    "Bajrang Vihar Colony,Darpan Colony",
                    "Bankers Colony,Darpan Colony",
                    "Bhao Ka Bazar,Bakshi Ki Goth",
                    "Chandan Colony",
                    "Chetak Puri Lashkar",
                    "City Centre Mahalgoan",
                    "Dahi Mandi,Sarafa Bazar ",
                    "Chanakya Puri ,Darpan Colony",
                    "Chawri Bazar, Bakshi Ki Goth",
                    "Dal Bazar",
                    "Daulat Gunj",
                    "Darpan Colony",
                    "Jai Vilas Parisar(Lashkar)",
                    "Jayendra Gunj(Shinde Ki Chhawani)",
                    "Laxmi Colony",
                    "Mlb Colony(Lashkar)",
                    "New Kushak Nagar",
                    "Phool Bagh(Lashkar)",
                    "Police Colony",
                    "Dal Bazar",
                    "Defence Colony(Gandhinagar)",
                    "Dwarakapuri(Lashkar)",
                    "Gandhi Nagar",
                    "Harishankar Puram(Shriram Colony)",
                    "Katigali",
                    "Lalitpur Colony",
                    "Lashkar",
                    "Maharanapratap Nagar",
                    "Naya Bazar",
                    "Pardhi Mohalla",
                    "Sbi Colony",
                    "Shinde Ki Chhaoni",
                    "Shivaji Colony",
                    "Dahi Mandi(Sarafa Bazar)",
                    "Dailat Ganj",
                    "Didwana Oli(Daualat Ganj)",
                    "Durga Puri",
                    "Gastia Tazia Chouraha(Daualat Ganj)",
                    "Geeta Colony(Lashkar)",
                    "Ghosipura",
                    "Gubbara Phatak(Daal Bazar)",
                    "Helipad Colony(Lashkar)",
                    "Jinsivala",
                    "Jivaji Ganj",
                    "Jiyaji Chowk",
                    "Kampoo",
                    "Khasi Bazar",
                    "Khurjewala Mohalla",
                    "Laxmi Ganj",
                    "Madhav Ganj",
                    "Madhav Nagar",
                    "Mor Bazar",
                    "Nagarik Sahakari Bank",
                    "Nawab Singh Colony(Harishankar Puram)",
                    "Panchvati Nagar",
                    "Pant Nagar(Mohalgaon)",
                    "Patankar Chauraha(Khurjewala Mohalla)",
                    "Payga Colony",
                    "Pragati Nagar",
                    "Prem Nagar",
                    "Raghavendra Nagar(Gwalior)",
                    "Railway Colony",
                    "Rati Nagar",
                    "Roshini Ghar",
                    "Mohalla(Lashkar)",
                    "Saket Nagar",
                    "Sarafa Bazar(Daulat Ganj)",
                    "Sathe Ki Goth",
                    "Satuadev Nagar",
                    "Seva Nagar",
                    "Servak Nagar",
                    "Shankar Chowk",
                    "Shankar Colony",
                    "Shek Ki Bagiya",
                    "Sukhar Colony(Dana Oli)",
                    "Surya Nagar",
                    "Jawahar Colony(Lashkar)",
                    "Gandhi Market(Jiyaji Chowk)",
                    "Ghasmandi",
                    "Ghauspura",
                    "Hazira Chowk(Tansen Nagar)",
                    "Hanuman Chouraha(Shekh Ki Bagiya)",
                    "Hargovindouram(Tulsi Vihar Nagar)",
                    "Janak Ganj(Jiyaji Chowk)",
                    "Kailash Vihar",
                    "Kuswah Mohalla(Shilpa Studio)",
                    "Lalaka Bazar",
                    "Loha Mandi",
                    "Mama Ka Bazar",
                    "Navgrah Colony",
                    "New Colony",
                    "New Vivek Nagar",
                    "Nimbaji Ki Khoh(Laxmi Gunj)",
                    "Panchvati Colony(Ghospura)",
                    "Patel Nagar",
                    "Raj Mandi",
                    "Ratan Colony(Shek Ki Bagiya)",
                    "Saraswati Nagar",
                    "Sath Bhai Ki Goth",
                    "Sbi Chauraha",
                    "Scindia Nagar",
                    "Shada Vihar(Mahalgaon)",
                    "Sri Vihar Colony(Ghosipura)",
                    "Shubashnagar(Birla Nagar)",
                    "Darpan Colony",
                    "Janak Taal(Gurunanak Nagar)",
                    "Dholi Bua Kapil(Shri Ram Colony)",
                    "Ekata Nagar(Vinay Nagar)",
                    "Fort View Colony",
                    "Gadway Ki Goth(Lala Ki Bazar)",
                    "Ganjiwala Mohalla",
                    "Gargaj Colomny(Laxmipuram)",
                    "Golpahariya",
                    "Govindpuri",
                    "Gurunanak Nagar",
                    "Hanuman Nagar(Morar)",
                    "Indramani Nagar",
                    "Jagrati Nagar",
                    "Jiwaji University Chauraha",
                    "Mahalgaon",
                    "Mayur Nagar",
                    "Nehru Colony",
                    "New Govindpuri(Mahalgaon)",
                    "New Resham Colony",
                    "Paras Vihar Colony",
                    "Radhika Vihar(Madhav Gunj)",
                    "Ranji Ka Pura",
                    "Ranipura",
                    "Sadashiv Nagar(Vinay Nagar)",
                    "Samadhiya Colony(Kala Saiyad)",
                    "Shakuntlapuri",
                    "Shastri Nagar(Thatipur)",
                    "Shiv Sadan",
                    "Shivaji Nagar Thatipur",
                    "Sikander Kampo(Chana Kothar)",
                    "Shashtri Nagar, Thatipur",
                    "Shinde Ki Chhwani",
                    "Shiv Shaktipuram",
                    "Shivaji Colony",
                    "Shri Vihar Colony, Ghosipura",
                    "Subhash Nagar, Birla Nagar",
                    "Sukkhar Colony, Dana Oli",
                    "Surya Nagar",
                    "Tagore Nagar, Patel Nagar",
                    "Tansen Nagar",
                    "Tansen Residency Chauraha",
                    "Thatipur Gaon",
                    "Vasant Vihar, Lashkar",
                    "Vijay Nagar",
                    "Vijay Nagar Extension, Basvanth Vihar Colony",
                    "Vikas Nagar, Lashkar",
                    "Vinay Nagar Chowk",
                    "Vivek Vihar",
                    "Suresh Nagar, Thatipur",
                    "Thatipur",
                    "Shivaji Nagar, Thatipur",
                    "Shri Ram Nagar Colony",
                    "Yamuna Nagar, Darpan Colony"
            };
}
