package com.user.foodzamo.OrderFood;

/**
 * Created by user on 12/17/2016.
 */

public class LocParams {
    public String below_five[]={
            "Alkapuri",
            "Anupam Nagar Patel Nagar",
            "Balwant Nagar",
            "Bank Colony Mahalgaon",
            "Bajrang Vihar Colony,Darpan Colony",
            "Bankers Colony,Darpan Colony",
            "Chetak Puri Lashkar",
            "Chanakya Puri ,Darpan Colony",
            "Darpan colony",
            "Kailash Nagar(Mahalgaon)",
            "Kailash Vihar(Tusi Vihar Colony)",
            "Krishna Vihar(Thatipur)",
            "Kampoo",
            "Lashkar",
            "Madhav Nagar",
            "Madhuwan Enclave(Mahalgaon)",
            "Mahalgaon",
            "Mayur Nagar(Thatipur)",
            "Nawab Singh Colony(Harishankar Colony)",
            "Nehru Colony(Thatipur)",
            "New Govindpuri(Mahalgaon)",
            "New Vivek Nagar(Thatipur)",
            "Pant Nagar(Mahalgaon)",
            "Shastri Nagar(Thatipur)",
            "Sharda Vihar(Mahalgaon)",
            "Ravi nagar(Lashkar)",
            "Roshini Ghar(Lashkar)",
            "Saketnagar(Durgapuri)",
            "Saraswati Nagar",
            "Satyadev Nagar",
            "Patel Ngar",
            "Phool Bagh(Lashkar)",
            "Police Colony",
            "Raghavendra Nagar",
            "Railway Colony(Thatipur)",
            "Ramanuj Nagar",
            "Defence COlony(Gandhinagar)",
            "Durgapuri",
            "Gandhinagar",
            "Govindpuri",
            "Hargovindpuram(Tulsi vihar nagar)",
            "Harishankarpuram(Shri ram colony)",
            "Helipad Colony(Lashkar",
            "Hurawali",
            "Indramani Nagar(Thatipur)",
            "Shastri Nagr Thatipur",
            "Shivaji Colony",
            "Tagore Nagar, Patel Nagar",
            "Tansen Residency Chauraha",
            "Thatipur Gaon, Thatipur",
            "Vasant Vihar, Lashkar",
            "Vijay Nagar",
            "Vijay Nagar Extension, Basvant Vihar Colony",
            "Vikas Nagar, Lashkar",
            "Vivek Vihar",
            "Suresh Nagar, Thatipur",
            "Thatipur",
            "Shivaji Nagar, Thatipur",
            "Shri Ram Nagar Colony",
            "Yamuna Nagar, Darpan Colony",
            "Kumharpura Chauraha(Dardan COlony)",
            "Laxmi Colony",
            "Maharana Pratap nagar(Lashkar)",
            "Mahaver Bhavan(Morar)",
            "MLB Colony(Lashkar)",
            "Nagarik Sahakar Bank",
            "City Centre Mahalgoan",
            "Panchivati Nagar(Lashkar)",
            "Jai villas parijar(Lashkar)"
    };
}
