package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocSpice {
    public String below_five[]={
            "Achileshwar Mandir",
            "Adarsh Colony Shinde Ki Chhawani",
            "Alkapuri",
            "Amkoh",
            "Anupam Nagar Patel Nagar",
            "Bala Bai Ka Bazar, Lohiya Bazar",
            "Balwant Nagar",
            "Bank Colony Mahalgaon",
            "Bhao Ka Bazar,Bakshi Ki Goth",
            "Cancer Pahadi",
            "Chana Kothar",
            "Chandan Colony",
            "Chatri Sabji Mandi,Jiyaki Chowk",
            "Chawri Bazar, Bakshi Ki Goth",
            "Chetak Puri Lashkar",
            "City Centre Mahalgoan",
            "Dahi Mandi,Sarafa Bazar ",
            "Dal Bazar",
            "Daulat Gunj",
            "Dahi Mandi",
            "Dal Bazar",
            "Daulat Ganj",
            "Geeta Colony(Daal Bazar,Lashkar)",
            "Helipad Colony(Lashkar)",
            "Jai Vilas Pariyar(Lashkar)",
            "Lalitpur Colony",
            "Lashkar",
            "Maharanapratap Nagar",
            "Payga Colony",
            "Roshini Ghar",
            "Sbi Colony",
            "Shankar Chowk",
            "Shankar Colony",
            "Dahi Mandi(Sarafa Bazar)",
            "Dal Bazar",
            "Daulat Ganj",
            "Jawahar Colony(Lashkar)",
            "Didwana Oli(Daulat Ganj)",
            "Gastka Tazia Chauraha(Daulant Ganj)",
            "Gubbara Phatak(Daal Bazaar)",
            "Jayendra Gunj(Shinde Ki Chhawani)",
            "Jinsinala",
            "Khurjewala Mohalla",
            "Lohiya Bazar",
            "Nagarik Sahakari Bank",
            "Naya Bazar",
            "Paras Vihar Colony",
            "Pardhi Mohalla",
            "Patankar Chauraha(Khurjewala Mohalla)",
            "Sarafa Bazar(Daulat Ganj)",
            "Gadwayki Goth(Lala Ki Bazar)",
            "Gandhi Market(Jiyaji Chowk)",
            "Ganjiwala Mohalla",
            "Harishshankar Puram(Shri Ram Colony)",
            "Jivaji Chowk",
            "Katigati",
            "Lalaka Bazar",
            "Madhav Ganj",
            "Madhav Nagar",
            "Mama Ka Bazar",
            "Nawab Singh Colony(Harishshankar Puram)",
            "New Prem Nagar",
            "Pant Nagar(Mahalgaon)",
            "Phool Bagh(Lashkar)",
            "Radhika Vihar(Madhav Gunj)",
            "Sathe Ki Goth",
            "Sbi Chauraha",
            "Shekh Ki Bagiya",
            "Sikander Kampoo(Chana Kothar)",
            "Sukkhar Colony(Dana Oli)",
            "Dholi Bua Kapul(Shri Ram Colony)",
            "Dwaraka Puri( Lashkar)",
            "Golpahariya",
            "Guda Gudi Ka Nakar(Lashkar)",
            "Hemsingh Ki Pared",
            "Jagrati Nagar",
            "Janak Ganj( Jiyaji Chowk)",
            "Jivaji Ganj",
            "Jiyaji Chowk",
            "Khasi Bazar",
            "Lohamandi",
            "Mor Bazar",
            "Navgrah Colony",
            "New Kushak Nagar",
            "New Payga Gudi",
            "Police Colony",
            "Pragati Nagar",
            "Ratan Colony(Shekh Ki Bagiya)",
            "Rati Nagar",
            "Ravi Nagar(Lashkar)",
            "Rm Colony",
            "Samadhiya Colony(Kala Saiyad)",
            "Sath Bhai Ki Goth",
            "Scindia Nagar",
            "Sharda Vihar(Mahalgaon)",
            "Shinde Ki Chhaoni",
            "Shivaji Colony",
            "Shivaji Nagar",
            "Shri Krishna Colony",
            "Surya Nagar",
            "Defence Colony(Gandhinagar)",
            "Gandhinagar",
            "Hargovindpuram(Tulsi Vihar Nagar)",
            "Kailash Vihar",
            "Kala Saiyad",
            "Laxmi Colony",
            "Madhwan Colony",
            "Mahalgaon",
            "Mlb Colony (Lashkar)",
            "New Govindpuri(Mahalgaon)",
            "Panchivati Nagar",
            "Panchwati Colony(Ghosipura)",
            "Patel Nagar",
            "Prem Nagar",
            "Pritampuram Colony",
            "Sadashiv Nagar( Vinay Nagar)",
            "Seva Nagar",
            "Sewak Nagar",
            "Shri Vihar Colony(Ghosipura)",
            "Shri Ram Colony",
            "Sikander Colony",
            "Shastri Nagar, Thatipur",
            "Shinde Ki Chhawani",
            "Shiv Shaktipuram",
            "Shivaji Colony",
            "Shri Vihar Colony, Ghosipura",
            "Sikander Kampo, Chana Kothat",
            "Shri Krishna Colony, Hem Singh Ki Pared",
            "Sukkhar Colony, Dana Oli",
            "Surya Nagar",
            "Tagore Nagar, Patel Nagar",
            "Tansen Residency Chauraha",
            "Tara Ganj, Loha Mandi, Gol Pahariya",
            "Thatiput Gaon, Thatipur",
            "Tilak Nagar, Radhika Nagar",
            "Vasant Vihar, Lashkar",
            "Vijay Nagar",
            "Vijay Nagar Extension, Basvant Vihar Colony",
            "Vikas Nagar, Lashkar",
            "Vinay Nagar Chowk",
            "Vivek Vihar",
            "Yadav Colony, Lashkar",
            "Shiv Sadan"

    };
}
