package com.user.foodzamo.OrderFood;

/**
 * Created by user on 11/27/2016.
 */

public class LocVolga {
    public String below_five[]=
            {
                    "Achileshwar Mandir",
                    "Adarsh Colony Shinde Ki Chhawani",
                    "Alkapuri",
                    "Amkoh",
                    "Anupam Nagar Patel Nagar",
                    "Apna Ghar Colony Vinay Nagar",
                    "Ashok Vihar Colony",
                    "Bala Bai Ka Bazar, Lohiya Bazar",
                    "Balwant Nagar",
                    "Bank Colony Mahalgaon",
                    "Bhao Ka Bazar,Bakshi Ki Goth",
                    "Bhodapur ,Anand Nagar",
                    "Cancer Pahadi",
                    "Chana Kothar",
                    "Chandan Colony",
                    "Chatri Sabji Mandi,Jiyaki Chowk",
                    "Chawri Bazar, Bakshi Ki Goth",
                    "Chetak Puri Lashkar",
                    "City Centre Mahalgoan",
                    "Dahi Mandi,Sarafa Bazar",
                    "Dal Bazar",
                    "Dahi Mandi (Sarafa Bazar)",
                    "Dal Bazar",
                    "Daulat Ganj",
                    "Didwana Ali ( Daulant Ganj)",
                    "Gastka Tazia Chouraha (Daulant Ganj)",
                    "Geeta Colony,Dal Bazaar(Lashkar)",
                    "Gubbala Phatak(Daal Bazar)",
                    "Helipad Colony(Lashkar)",
                    "Jai Vilas Parisar(Lashkar)",
                    "Jayendra Gunj(Shinde Ki Chhawani)",
                    "Lalitpur Colony",
                    "Lashkar",
                    "Pardhi Mohalla",
                    "Patankar Chauraha(Khurjewala Mohalla)",
                    "Payga Colony",
                    "Phool Bagh(Lashkar)",
                    "Roshini Ghar",
                    "Sbi Colony",
                    "Shankar Chowk",
                    "Shankar Colony                     ",
                    "Dwaraka Puri(Lashkar)",
                    "Gandhi Market,Chauri Bazar,Khagibazar(Jiyaji Chowk)",
                    "Ghosipura",
                    "Hanuman Chauraha(Shekh Ki Bagiya)",
                    "Jinsinala",
                    "Jivaji Chowk",
                    "Jiyaji Chowk",
                    "Katigati",
                    "Khurjewala Mohalla",
                    "Laxmi Ganj",
                    "Lohiya Bazar",
                    "Maharanapratap Nagar",
                    "Mor Bazar",
                    "Nagarik Sahakari Bank",
                    "Naya Bazar",
                    "New Kushak Nagar",
                    "New Prem Nagar",
                    "Police Colony",
                    "Rati Nagar",
                    "Ravi Nagar(Lashkar)",
                    "Sarafa Bazar(Daulant Ganj)",
                    "Sathe Ki Goth",
                    "Sbi Chauraha",
                    "Shekh Ki Bagiya",
                    "Shekh Ki Chhaoni",
                    "Shivaji Colony",
                    "Sukkhar Colony(Dana Oli)",
                    "Surya Nagar",
                    "Jawahar Colony(Lashkar)",
                    "Defence Colony(Gandhinagar)",
                    "Gadway Ki Goth(Lala Ki Bazar)",
                    "Gandhinagar",
                    "Ganjiwala Mohalla",
                    "Golpahariya",
                    "Harishankarpuram(Shri Ram Colony)",
                    "Jagrati Nagar",
                    "Janak Ganj(Jiyaji Chowk)",
                    "Jivaji Ganj",
                    "Kampoo",
                    "Sewak Nagar",
                    "Sri Vihar Colony(Ghosipura)",
                    "Kuswah Mohalla(Shilpa Studio)",
                    "Lalaka Bazar",
                    "Laxmi Colony",
                    "Loha Mandi",
                    "Madhav Ganj",
                    "Mamaka Bazar",
                    "Mlb Colony(Lashkar)",
                    "Nimbaji Ki Khoh(Laxmi Gunj)",
                    "Panchwati Colony(Ghosipura)",
                    "Pant Nagar(Mahalgaon)",
                    "Pragati Nagar",
                    "Prem Nagar",
                    "Radhika Nagar(Madhav Gunj)",
                    "Ratan Colony(Shekh Ki Bagiya)",
                    "Sathbhai Ki Goth",
                    "Scindia Nagar",
                    "Seva Nagar",
                    "Radhika Nagar",
                    "Janak Taal(Gurunanak Colony)",
                    "Dholi Bua Kapul(Shri Ram Colony)",
                    "Durga Puri",
                    "Ekata Nagar(Vinay Nagar)",
                    "Fort View Colony",
                    "Gargaj Colony( Laxmipuram)",
                    "Ghauspura",
                    "Gurunanak Nagar",
                    "Madhav Nagar",
                    "Navgrah Colony",
                    "Nawab Singh Colony(Harishankarpuram)",
                    "Panchivati Nagar",
                    "Paras Vihar Colony",
                    "Prem Nagar",
                    "Radhika Vihar( Madhav Gunj)",
                    "Raghavendra",
                    "Railway Colony",
                    "Raj Mandi",
                    "Ramji Ka Pura",
                    "Ramtapura",
                    "Rm Colony",
                    "Mohalla(Lashkar)",
                    "Sadashiv Nagar(Vinay Nagar)",
                    "Samadhiya Colony(Kala Saiyad)",
                    "Satyadev Nagar",
                    "Shiv Sadan",
                    "Sikander Kampo(Chana Kothar)",
                    "Shri Krishna Colony",
                    "Ghosmandi",
                    "Gudagudi Ka Nakar(Daal Bazar)",
                    "Hazira Chowk(Tansen Road)",
                    "Hargovindpuram(Tulsi Vihar Nagar)",
                    "Hemsingh Ki Pared",
                    "Kailash Vihar",
                    "Kala Saiyad",
                    "Laxmipuram(Kishan Bagh)",
                    "Madhwan Enclave",
                    "Mahalgaon",
                    "Mayur Nagar",
                    "New Colony",
                    "New Payga Gudi",
                    "Patel Nagar",
                    "Pritampuram Colony",
                    "Ranipura",
                    "Saraswati Nagar",
                    "Sharda Vihar(Mahalgaon)",
                    "Shivaji Nagar",
                    "Shubhash Nagar(Birla Nagar)",
                    "Shastri Nagar, Thatipur",
                    "Shinde Ki Chawani",
                    "Shiv Shaktipuram",
                    "Shivaji Colony",
                    "Shri Vihar Colony, Ghosipura",
                    "Sikander Kampo, Chana Kothar",
                    "Shri Krishna Colony, Hem Singh Ki Pared",
                    "Shubhash Nagar, Birla Nagar",
                    "Sukkhar Colony, Dana Oli",
                    "Surya Nagar",
                    "Tagore Nagar, Patel Nagar",
                    "Tansen Nagar",
                    "Tansen Residency Chauraha",
                    "Tara Ganj, Loha Mandi, Gol Pahariya",
                    "Thatipur Gaon, Thatipur",
                    "Tilak Nagar, Radhika Nagar",
                    "Vasant Vihar",
                    "Vijay Nagar",
                    "Vijay Nagar Extension, Basvant Vihar Colony",
                    "Vikas Nagar, Lashkar",
                    "Vinay Nagar",
                    "Vinay Nagar, Chowk",
                    "Vivek Vihar",
                    "Yadav Colony"
            };
}
